name: docsearch抓取

on: 
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    name: docsearch抓取
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 18
          cache: yarn

      - name: docsearch抓取
        env:
          app代碼: "70GEOCJCSX"
          API_金鑰: "b8504bd49b99826b1f7f7ccb8d9dadc8 "
        run: |
          docker run \
          -e app代碼 -e API_金鑰 \
          -e CONFIG="$(cat ..json)" \
          algolia/docsearch-scraper
